### PR TITLE
feat: init plugin with PrismJS theme and plugins

### PR DESCRIPTION
**Pull request by hsablonniere**
Plugins :
- prism-unescaped-markup to simplify HTML code examples
- prism-normalize-whitespace to avoid silly indentation in HTML slides

### CODE REVIEW

**Comment by hsablonniere** [comment]
@mojavelinux WDYT?

**Comment by mojavelinux** [comment]
Sent code review PR #3.

Take note of the fact that I locked the version of karma and socket.io. This is the only way I know to make prevent the tests from hanging on shutdown. I've read thread after thread about this and I absolutely don't understand why they can't fix this problem...but sticking to these versions gets the job done for now.

I also moved and modules that are required by the plugin from devDependencies to dependencies. This allows browserify to find these modules when this plugin is used in another project. The alternative is to add instructions to usage that explains that these dependencies must be added when using this plugin through browserify.

**Comment by mojavelinux** [comment]
In the future, could you send the pull request from your own fork? I think that keeps the upstream cleaner because the branches don't get listed alongside releases.

**Comment by mojavelinux** [comment]
There's one step that needs to be completed before we can do a release. Since npmjs.com doesn't yet support README files in AsciiDoc, I create a file named package-README.md using the template below, then I convert it to a JavaScript string and put it inside the readme field of the package.json file.

``````
# bespoke-PLUGIN_NAME

PLUGIN_DESCRIPTION

## Usage

This plugin is shipped in a [UMD format](https://github.com/umdjs/umd), meaning it is available as a CommonJS/AMD module or as a browser global.

For example, when using CommonJS modules:

```js
var bespoke = require('bespoke'),
  PLUGIN_NAME = require('bespoke-PLUGIN_NAME');

bespoke.from('.deck', [
  PLUGIN_NAME()
]);
```

When using browser globals:

```js
bespoke.from('.deck', [
  bespoke.plugins.PLUGIN_NAME()
]);
```

For more information about options and how the plugin works, see the [complete README](https://github.com/opendevise/bespoke-PLUGIN_NAME/blob/master/README.adoc).

## License

[MIT License](http://en.wikipedia.org/wiki/MIT_License)
``````

You can see an example here: https://github.com/opendevise/bespoke-fullscreen/blob/v1.0.0/package.json#L60

**Pull request merged**
